### ISSUE TITLE
Do you know CRC check? 

### ISSUE THREAD

**Issue by showtan001** [Marcello168/react-native-multi-serial-port#1]
/**************************************************************
功能： CRC校验(CRC check)
pcMess: 待求数据的首指针(The first pointer of the data to be requested)
wLen  : 待求数据的长度(The length of the data to be sought)
***************************************************************/
unsigned int crcVal1(unsigned char *pcMess,unsigned int wLen)
{
​long MSBInfo;
​int i,j ;
​unsigned int nCRCData;
 
​nCRCData = 0xffff;
​for(i = 0; i < wLen;i++)
​{
​​pcMess[i]&=0x00ff;
​​nCRCData = nCRCData ^ pcMess[i] ;
​​for(j= 0 ; j < 8 ;j ++)
​​{
​​​MSBInfo = nCRCData & 0x0001;
​​​nCRCData = nCRCData  >> 1;
​​​if(MSBInfo != 0 )
​​​​nCRCData = nCRCData ^ 0xa001;
​​}
​}
​return nCRCData;
}

I don't know C language, help me!

**Comment by Mase9527** [comment]
> /**************************************************************
> 功能： CRC校验(CRC check)
> pcMess: 待求数据的首指针(The first pointer of the data to be requested)
> wLen : 待求数据的长度(The length of the data to be sought)
> ***************************************************************/
> unsigned int crcVal1(unsigned char *pcMess,unsigned int wLen)
> {
> ​long MSBInfo;
> ​int i,j ;
> ​unsigned int nCRCData;
> 
> ​nCRCData = 0xffff;
> ​for(i = 0; i < wLen;i++)
> ​{
> ​​pcMess[i]&=0x00ff;
> ​​nCRCData = nCRCData ^ pcMess[i] ;
> ​​for(j= 0 ; j < 8 ;j ++)
> ​​{
> ​​​MSBInfo = nCRCData & 0x0001;
> ​​​nCRCData = nCRCData >> 1;
> ​​​if(MSBInfo != 0 )
> ​​​​nCRCData = nCRCData ^ 0xa001;
> ​​}
> ​}
> ​return nCRCData;
> }
> 
> I don't know C language, help me!

什么鬼 网上有很多例子啊
